global using System;
global using System.ComponentModel;
global using System.Diagnostics;
global using DotNetWhere.Application.Commands;
global using DotNetWhere.Application.Infrastructure;
global using DotNetWhere.Application.Loggers;
global using DotNetWhere.Core;
global using Microsoft.Extensions.DependencyInjection;
global using Spectre.Console;
global using Spectre.Console.Cli;
global using ElapsedTime = System.TimeSpan;